development:
  adapter: postgresql
  database: padrinhosnet_development

test:
  adapter: postgresql
  database: padrinhosnet_test

production:
  adapter: postgresql
  database: padrinhosnet_production
